use_frameworks!
platform :ios, '11.0'
target 'CXPopupKit_Example' do
  pod 'CXPopupKit', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'CXPopupKit_Tests' do
    inherit! :search_paths
  end
end
